# Generated by Django 4.1.2 on 2022-10-31 11:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file_attachment', models.FileField(blank=True, null=True, upload_to='course_Attachment/pdfs/')),
                ('description', models.TextField()),
                ('thumbnail_url', models.CharField(max_length=100)),
                ('course_type', models.CharField(choices=[('FREE', 'FREE'), ('PAID', 'PAID')], default='FREE', max_length=4)),
                ('course_length', models.CharField(max_length=20)),
                ('course_slug', models.SlugField(default='-')),
                ('course_price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StudentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
