# Generated by Django 4.1.2 on 2022-10-26 22:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("practice", "0007_alter_answers_answer"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentProcess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.CharField(default="-", max_length=50)),
                ("payment_status", models.BooleanField(default=False)),
                ("datestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "examPractice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="practice.exams"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExamSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("DateStamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("progress", models.CharField(default="0 %", max_length=10)),
                ("payment_id", models.CharField(default="-", max_length=50)),
                ("order_id", models.CharField(default="-", max_length=50)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "examPractice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="practice.exams"
                    ),
                ),
            ],
        ),
    ]
