# Generated by Django 4.1.2 on 2022-10-23 23:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("practice", "0002_rename_fullname_users_fullname_and_more")]

    operations = [
        migrations.CreateModel(
            name="Quastion_db",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "questionCategory",
                    models.CharField(
                        choices=[
                            (
                                "QUESTION TYPE_BEGINNERS",
                                (
                                    ("I.1. traffic light", "I.1. TRAFFIC LIGHT "),
                                    ("I.2. ubwikorezi", " I.2. UBWIKOREZI"),
                                    (
                                        "I.3. ibyerekeyekugenda mu muhanda",
                                        " I.3. IBYEREKEYE KUGENDA MU MUHANDA",
                                    ),
                                ),
                            ),
                            (
                                "QUESTION TYPE_INTERMEDIATE",
                                (
                                    ("II.1. traffic light", "II.1. TRAFFIC LIGHT "),
                                    ("II.2. ubwikorezi", " II.2. UBWIKOREZI"),
                                    (
                                        "II.3. ibyerekeyekugenda mu muhanda",
                                        " II.3. IBYEREKEYE KUGENDA MU MUHANDA",
                                    ),
                                ),
                            ),
                            (
                                "QUESTION TYPE_ADVANCED",
                                (
                                    ("III.1. traffic light", "III.1. TRAFFIC LIGHT "),
                                    ("III.2. ubwikorezi", " III.2. UBWIKOREZI"),
                                    (
                                        "III.3. ibyerekeyekugenda mu muhanda",
                                        " III.3. IBYEREKEYE KUGENDA MU MUHANDA",
                                    ),
                                ),
                            ),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("questionName", models.TextField(max_length=500)),
                ("optionA", models.CharField(max_length=100)),
                ("optionB", models.CharField(max_length=100)),
                ("optionC", models.CharField(max_length=100)),
                ("optionD", models.CharField(max_length=100)),
                (
                    "answer",
                    models.CharField(
                        choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                        max_length=1,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="answers",
            name="aded_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="candidates",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="exams",
            name="createdby",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="exams",
            name="exam_status",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="marks",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="createdby",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="questionCategory",
            field=models.CharField(
                choices=[
                    (
                        "QUESTION TYPE_BEGINNERS",
                        (
                            ("I.1. traffic light", "I.1. TRAFFIC LIGHT "),
                            ("I.2. ubwikorezi", " I.2. UBWIKOREZI"),
                            (
                                "I.3. ibyerekeyekugenda mu muhanda",
                                " I.3. IBYEREKEYE KUGENDA MU MUHANDA",
                            ),
                        ),
                    ),
                    (
                        "QUESTION TYPE_INTERMEDIATE",
                        (
                            ("II.1. traffic light", "II.1. TRAFFIC LIGHT "),
                            ("II.2. ubwikorezi", " II.2. UBWIKOREZI"),
                            (
                                "II.3. ibyerekeyekugenda mu muhanda",
                                " II.3. IBYEREKEYE KUGENDA MU MUHANDA",
                            ),
                        ),
                    ),
                    (
                        "QUESTION TYPE_ADVANCED",
                        (
                            ("III.1. traffic light", "III.1. TRAFFIC LIGHT "),
                            ("III.2. ubwikorezi", " III.2. UBWIKOREZI"),
                            (
                                "III.3. ibyerekeyekugenda mu muhanda",
                                " III.3. IBYEREKEYE KUGENDA MU MUHANDA",
                            ),
                        ),
                    ),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
