# Generated by Django 4.1.2 on 2022-10-24 13:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [("practice", "0003_quastion_db_alter_answers_aded_by_and_more")]

    operations = [
        migrations.AddField(
            model_name="exams",
            name="end_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="exams",
            name="start_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
