# Generated by Django 4.1.2 on 2022-10-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("practice", "0004_exams_end_time_exams_start_time")]

    operations = [
        migrations.AddField(
            model_name="question",
            name="optionE",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="optionF",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="answer",
            field=models.CharField(
                choices=[
                    ("A", "A"),
                    ("B", "B"),
                    ("C", "C"),
                    ("D", "D"),
                    ("E", "E"),
                    ("F", "F"),
                ],
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="optionA",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="optionB",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="optionC",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="optionD",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="question",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
