# Generated by Django 4.1.2 on 2022-10-26 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0006_quastion_db_optione_quastion_db_optionf_and_more")
    ]

    operations = [
        migrations.AlterField(
            model_name="answers",
            name="answer",
            field=models.CharField(
                choices=[
                    ("A", "B"),
                    ("B", "B"),
                    ("C", "C"),
                    ("D", "D"),
                    ("E", "E"),
                    ("F", "F"),
                ],
                max_length=1,
            ),
        )
    ]
