# Generated by Django 4.1.2 on 2022-10-27 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [("practice", "0007_alter_answers_answer")]

    operations = [
        migrations.RenameField(
            model_name="answers", old_name="question", new_name="question_id"
        ),
        migrations.RenameField(
            model_name="candidates", old_name="exam", new_name="exam_id"
        ),
        migrations.RenameField(
            model_name="marks", old_name="exam_name", new_name="exam_id"
        ),
        migrations.RenameField(
            model_name="question", old_name="exam_name", new_name="exam_id"
        ),
        migrations.RenameField(
            model_name="set", old_name="exam_name", new_name="exam_id"
        ),
        migrations.RemoveField(model_name="candidates", name="timestamps"),
        migrations.RemoveField(model_name="candidates", name="user"),
        migrations.RemoveField(model_name="exams", name="timestamps"),
        migrations.RemoveField(model_name="marks", name="status"),
        migrations.RemoveField(model_name="marks", name="timestamps"),
        migrations.RemoveField(model_name="marks", name="user"),
        migrations.AddField(
            model_name="candidates",
            name="answered",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="candidates",
            name="attempt_no",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="candidates",
            name="registered",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="candidates",
            name="registered_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="candidates",
            name="user_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="candidates",
            name="view_answers",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="exams",
            name="attempts_allowed",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="exams",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="exams",
            name="description",
            field=models.TextField(blank=True, null="True"),
            preserve_default="True",
        ),
        migrations.AddField(
            model_name="exams",
            name="modified",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="exams",
            name="pass_percentage",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="marks",
            name="answer",
            field=models.TextField(blank=True, null="True"),
            preserve_default="True",
        ),
        migrations.AddField(
            model_name="marks",
            name="registration_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="practice.candidates",
            ),
        ),
        migrations.AddField(
            model_name="marks", name="verify", field=models.IntegerField(default=0)
        ),
        migrations.AlterField(
            model_name="answers",
            name="answer",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A", "B"),
                    ("B", "B"),
                    ("C", "C"),
                    ("D", "D"),
                    ("E", "E"),
                    ("F", "F"),
                ],
                max_length=1,
                null="True",
            ),
        ),
        migrations.AlterField(
            model_name="answers",
            name="timestamps",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="question",
            name="timestamps",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name="MatchTheColumns",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField(blank=True, null="True")),
                ("answer", models.TextField(blank=True, null="True")),
                (
                    "question_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="practice.question",
                    ),
                ),
            ],
        ),
    ]
