# Generated by Django 4.1.2 on 2022-10-29 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('title', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('starting_time', models.DateTimeField()),
                ('finishing_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=50, null=True)),
                ('order', models.IntegerField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='privateExams.exam')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('order', 'content')},
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_content', models.CharField(max_length=50)),
                ('answer_flag', models.BooleanField(default=False)),
                ('order', models.CharField(max_length=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='privateExams.question')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('order', 'answer_content')},
            },
        ),
    ]
