# Generated by Django 4.1.2 on 2022-10-21 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('privateExams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_content', models.CharField(max_length=50)),
                ('answer_flag', models.BooleanField(default=False)),
                ('order', models.CharField(max_length=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='privateExams.question')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('order', 'answer_content')},
            },
        ),
    ]
