# Generated by Django 4.1.2 on 2022-10-21 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('privateExams', '0002_answer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['al_order']},
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='order',
            new_name='al_order',
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('al_order', 'answer_content')},
        ),
    ]
