# Generated by Django 4.1.2 on 2022-10-22 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('privateExams', '0003_alter_answer_options_rename_order_answer_al_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['order']},
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='al_order',
            new_name='order',
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('order', 'answer_content')},
        ),
    ]
